services:
  broker:
    image: redis:7
    restart: unless-stopped
    volumes:
      - redisdata:/data
    networks:
      - default

  db:
    image: postgres:15
    restart: unless-stopped
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - default

  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    ports:
      - "18000:8000"
    depends_on:
      - db
      - broker
    volumes:
      - data:/usr/src/paperless/data
      - media:/usr/src/paperless/media
      - ./export:/usr/src/paperless/export
      - ./consume:/usr/src/paperless/consume
    env_file:
      - .env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_DBNAME: ${POSTGRES_DB}
      PAPERLESS_DBUSER: ${POSTGRES_USER}
      PAPERLESS_DBPASS: ${PAPERLESS_DBPASS}
      PAPERLESS_SECRET_KEY: ${PAPERLESS_SECRET_KEY}
      PAPERLESS_EXTRA_DEPS: "tesseract-ocr-deu tesseract-ocr-fra tesseract-ocr-eng tesseract-ocr-ltz"
      PAPERLESS_OCR_LANGUAGES: "deu fra eng ltz"
      PAPERLESS_OCR_LANGUAGE: "deu"
      PAPERLESS_AVAILABLE_LANGUAGES: "de,fr,en"
    networks:
      - default
      - reverse-proxy

networks:
  reverse-proxy:
    external: true
  default:

volumes:
  redisdata:
  pgdata:
  data:
  media: